TemplateApp/urls.py
from django.urls import path
from . import views

app_name='app'
urlpatterns=[
    path('home/',views.home,name='home'),
    path('members/',views.members,name='members'),
    path('member/<int:id>',views.member,name='member'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('TemplateApp.urls')),
]

TemplateApp/models.py
from django.db import models

# Create your models here.

TemplateApp/views.py
from django.shortcuts import render

# Create your views here.
class Member:
    def __init__(self,id,name,join_at,picture_path):
        self.id=id
        self.name=name
        self.join_at=join_at
        self.picture_path=picture_path

member_list= [
    Member(0,'Taro','2018/04/01','img/taro.jpg'),
    Member(1,'Jiro','2019/04/01','img/jiro.jpg'),
    Member(2,'Hanako','2019/05/01','img/hanako.jpg'),
    Member(3,'Yoshiko','2018/10/01','img/yoshiko.jpg'),
]

def home(request):
    return render(request,'TemplateApp/home.html')

def members(request):
    return render(request,'TemplateApp/members.html',context={
        'members':member_list
    })

def member(request,id):
    return render(request,'TemplateApp/member_detail.html',context={
        'member':member_list[id]
    })

templates/TemplateApp/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django大学陸上部{%endblock%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <nav class="navber navber-expand-lg nabver-light bg-light">
        <a class="navber-brand" href="{% url 'app:home' %}">Home</a>
        <a class="navber-brand" href="{% url 'app:members' %}">メンバー一覧</a>
    </nav>
    {% block content %}{% endblock %}
</body>
</html>

templates/TemplateApp/home.html
{% extends "TemplateApp/base.html" %}

{% block title %}ホーム{{ block.super }}{%endblock%}

{% block content %}
<p>Django大学陸上部ホーム</p>
{%endblock%}

templates/TemplateApp/member_detail.html
{% extends "TemplateApp/base.html" %}

{% block title %}メンバー詳細{{ block.super }}{%endblock%}

{% block content %}
{% load static %}
{% load custom_tags %}
<h1>メンバー詳細画面</h1>
 <img src="{% static member.picture_path %}">
 <p>名前：{{ member.name }}</p>
 <p>入部日：{{ member.join_at }}</p>
 <p>入部から：{{ member.join_at | calcurate_datetime_to_now }}</p>
{%endblock%}

templates/TemplateApp/members.html
{% extends "TemplateApp/base.html" %}

{% block title %}メンバー一覧{{ block.super }}{%endblock%}

{% block content %}
{% for member in members %}
<p><a href="{% url  'app:member' id=member.id %}">{{ member.name }}</p>
{% endfor %}
{%endblock%}